# Generated by Django 2.0 on 2020-12-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('director', models.CharField(max_length=300)),
                ('cast', models.CharField(max_length=1000)),
                ('description', models.TextField(max_length=5000)),
                ('release_Date', models.DateField()),
                ('average_Rating', models.FloatField(default=0)),
                ('seasons', models.CharField(max_length=300)),
                ('image', models.URLField(default=None, null=True)),
            ],
        ),
    ]
