# Generated by Django 2.0 on 2020-12-06 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Series',
            new_name='Seriess',
        ),
    ]
