# Generated by Django 2.0 on 2020-12-06 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_auto_20201206_1157'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seriess',
            new_name='Series',
        ),
    ]
